# Generated by Django 2.2.7 on 2020-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgMonthlyAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('mm_yyyy', models.CharField(max_length=7)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'unique_together': {('fin_year', 'treasury_code', 'mm_yyyy')},
            },
        ),
    ]
