# Generated by Django 2.2.7 on 2020-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReceiptMaster',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('tran_id', models.IntegerField()),
                ('major_head', models.CharField(max_length=4)),
                ('scheme_code', models.CharField(max_length=13)),
                ('ddo_code', models.CharField(blank=True, max_length=7)),
                ('party_name', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('entry_date', models.DateField()),
                ('user_code', models.CharField(max_length=4)),
                ('flag', models.CharField(max_length=2)),
                ('online_tran_id', models.IntegerField(blank=True)),
                ('voucher_no', models.IntegerField()),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptMaster',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('tran_id', models.IntegerField()),
                ('major_head', models.CharField(max_length=4)),
                ('scheme_code', models.CharField(max_length=13)),
                ('ddo_code', models.CharField(blank=True, max_length=7)),
                ('party_name', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('entry_date', models.DateField()),
                ('user_code', models.CharField(max_length=4)),
                ('flag', models.CharField(max_length=2)),
                ('online_tran_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSeq',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('tran_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherSeq',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('month', models.CharField(max_length=2)),
                ('major_head', models.CharField(max_length=4)),
                ('voucher_no', models.IntegerField()),
            ],
        ),
    ]
