# Generated by Django 2.2.7 on 2020-04-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpBillMaster',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('bill_no', models.IntegerField()),
                ('ddo_code', models.CharField(max_length=7)),
                ('scheme_code', models.CharField(max_length=17)),
                ('dept_bill_no', models.IntegerField()),
                ('detail_head', models.CharField(max_length=2)),
                ('bill_type', models.CharField(max_length=2)),
                ('detail_desc', models.CharField(max_length=50)),
                ('net_amt', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_ref_no', models.TextField()),
                ('bill_identifier', models.CharField(max_length=1)),
                ('file_upload_no', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('bill_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.BillMaster')),
            ],
        ),
        migrations.CreateModel(
            name='CmpTemp',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('bill_no', models.IntegerField()),
                ('account_no', models.CharField(max_length=30)),
                ('beneficiary_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('file_upload_no', models.IntegerField()),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CmpTransactionSeq',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('transaction_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CmpUploadSeq',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('file_upload_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalCmpBillMaster',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('bill_no', models.IntegerField()),
                ('ddo_code', models.CharField(max_length=7)),
                ('scheme_code', models.CharField(max_length=17)),
                ('dept_bill_no', models.IntegerField()),
                ('detail_head', models.CharField(max_length=2)),
                ('bill_type', models.CharField(max_length=2)),
                ('detail_desc', models.CharField(max_length=50)),
                ('net_amt', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_ref_no', models.TextField()),
                ('bill_identifier', models.CharField(max_length=1)),
                ('file_upload_no', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('bill_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.FinalBillMaster')),
            ],
        ),
        migrations.CreateModel(
            name='FinalCmpEmployeeDetails',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('bill_no', models.IntegerField()),
                ('account_no', models.CharField(max_length=30)),
                ('beneficiary_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('file_upload_no', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('final_cmp_bill_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sbi.FinalCmpBillMaster')),
            ],
        ),
        migrations.CreateModel(
            name='CmpEmployeeDetails',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('bill_no', models.IntegerField()),
                ('account_no', models.CharField(max_length=30)),
                ('beneficiary_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('file_upload_no', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('cmp_bill_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sbi.CmpBillMaster')),
            ],
        ),
    ]
