# Generated by Django 2.2.7 on 2020-04-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('bill_type', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('classification_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ddo',
            fields=[
                ('ddo_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('ddo_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('demand_no', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('dept_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailHead',
            fields=[
                ('detail_head', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MajorHead',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('demand_no', models.CharField(max_length=2)),
                ('major_head', models.CharField(max_length=4)),
                ('major_head_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MinorHead',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('demand_no', models.CharField(max_length=2)),
                ('major_head', models.CharField(max_length=4)),
                ('submajor_head', models.CharField(max_length=2)),
                ('minor_head', models.CharField(max_length=3)),
                ('minor_head_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('treasury_code', models.CharField(max_length=2)),
                ('operator_code', models.CharField(max_length=4)),
                ('operator_type', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=50)),
                ('password', models.TextField()),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchemes',
            fields=[
                ('scheme_code', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('scheme_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSchemes',
            fields=[
                ('scheme_code', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('scheme_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchemeHead',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('demand_no', models.CharField(max_length=2)),
                ('major_head', models.CharField(max_length=4)),
                ('submajor_head', models.CharField(max_length=2)),
                ('minor_head', models.CharField(max_length=3)),
                ('scheme_head', models.CharField(max_length=2)),
                ('scheme_head_name', models.TextField()),
                ('minor_head_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.MinorHead')),
            ],
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('treasury_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('treasury_name', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('treasury_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SubSchemeHead',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('demand_no', models.CharField(max_length=2)),
                ('major_head', models.CharField(max_length=4)),
                ('submajor_head', models.CharField(max_length=2)),
                ('minor_head', models.CharField(max_length=3)),
                ('scheme_head', models.CharField(max_length=2)),
                ('subscheme_head', models.CharField(max_length=2)),
                ('subscheme_head_name', models.TextField()),
                ('scheme_head_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.SchemeHead')),
            ],
        ),
        migrations.CreateModel(
            name='SubMajorHead',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('demand_no', models.CharField(max_length=2)),
                ('major_head', models.CharField(max_length=4)),
                ('submajor_head', models.CharField(max_length=2)),
                ('submajor_head_name', models.TextField()),
                ('major_head_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.MajorHead')),
            ],
        ),
        migrations.CreateModel(
            name='SubDetailHeads',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('detail_head', models.CharField(max_length=2)),
                ('subdetail_head', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('detail_head_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.DetailHead')),
            ],
        ),
        migrations.AddField(
            model_name='minorhead',
            name='submajor_head_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.SubMajorHead'),
        ),
        migrations.CreateModel(
            name='DeductionSchemes',
            fields=[
                ('scheme_code', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('flag', models.CharField(max_length=1)),
                ('receipt_scheme_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.ReceiptSchemes')),
            ],
        ),
        migrations.CreateModel(
            name='DdoSchemeMap',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('treasury_code', models.CharField(max_length=2)),
                ('ddo_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Ddo')),
                ('scheme_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.PaymentSchemes')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorDdoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddo_code', models.CharField(max_length=7)),
                ('operator_type', models.CharField(max_length=50)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Operators')),
            ],
            options={
                'unique_together': {('operator', 'ddo_code')},
            },
        ),
    ]
