# Generated by Django 2.2.7 on 2020-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineReceiptMaster',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_tran_id', models.IntegerField()),
                ('major_head', models.CharField(max_length=4)),
                ('scheme_code', models.CharField(max_length=13)),
                ('ddo_code', models.CharField(blank=True, max_length=7)),
                ('party_name', models.TextField()),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineReceiptSeq',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_tran_id', models.IntegerField()),
            ],
        ),
    ]
