# Generated by Django 2.2.7 on 2020-04-30 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentUsers',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('user_type', models.CharField(max_length=30)),
                ('demand_no', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineBillMaster',
            fields=[
                ('master_id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(blank=True, max_length=2, null=True)),
                ('online_bill_no', models.IntegerField(blank=True)),
                ('demand_no', models.CharField(blank=True, max_length=2, null=True)),
                ('ddo_code', models.CharField(max_length=7)),
                ('detail_head', models.CharField(max_length=2)),
                ('major_head', models.CharField(blank=True, max_length=4, null=True)),
                ('scheme_code', models.CharField(max_length=17)),
                ('dept_bill_no', models.IntegerField()),
                ('bill_type', models.CharField(max_length=2)),
                ('date', models.DateField()),
                ('net_amt', models.BigIntegerField()),
                ('gross_amt', models.BigIntegerField(blank=True, null=True)),
                ('status_flag', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineBillSeq',
            fields=[
                ('seq_id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_bill_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineGpfTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_bill_no', models.IntegerField()),
                ('sanction_no', models.TextField(blank=True)),
                ('amount', models.BigIntegerField(blank=True)),
                ('grade', models.IntegerField(blank=True)),
                ('master_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.OnlineBillMaster')),
            ],
            options={
                'unique_together': {('fin_year', 'treasury_code', 'online_bill_no')},
            },
        ),
        migrations.CreateModel(
            name='OnlineGpfDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_bill_no', models.IntegerField()),
                ('gpf_no', models.CharField(blank=True, max_length=20)),
                ('subscriber_name', models.CharField(blank=True, max_length=50)),
                ('amount', models.BigIntegerField(blank=True)),
                ('master_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.OnlineBillMaster')),
            ],
            options={
                'unique_together': {('fin_year', 'treasury_code', 'online_bill_no', 'gpf_no')},
            },
        ),
        migrations.CreateModel(
            name='OnlineBillSubDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_bill_no', models.IntegerField()),
                ('subdetail_head', models.CharField(blank=True, max_length=2)),
                ('amount', models.BigIntegerField(blank=True)),
                ('master_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.OnlineBillMaster')),
            ],
            options={
                'unique_together': {('fin_year', 'treasury_code', 'online_bill_no', 'subdetail_head')},
            },
        ),
        migrations.CreateModel(
            name='OnlineBillDeductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.CharField(max_length=9)),
                ('treasury_code', models.CharField(max_length=2)),
                ('online_bill_no', models.IntegerField()),
                ('scheme_code', models.CharField(blank=True, max_length=17)),
                ('major_head', models.CharField(blank=True, max_length=4)),
                ('amount', models.BigIntegerField(blank=True)),
                ('deduction_flag', models.CharField(blank=True, max_length=2)),
                ('master_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.OnlineBillMaster')),
            ],
            options={
                'unique_together': {('fin_year', 'treasury_code', 'online_bill_no', 'scheme_code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=30)),
                ('beneficiary_name', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('department_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentUsers')),
            ],
            options={
                'unique_together': {('account_no', 'ifsc', 'department_user')},
            },
        ),
    ]
